inherit_gem:
  rubocop-inst:
  - rubocop.yml

plugins:
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable

Naming/FileName:
  Exclude:
    - lib/mqtt-homeassistant.rb

Style/DocumentDynamicEvalDefinition:
  Enabled: false
Style/Documentation:
  Enabled: false
